<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NLLT421612" failures="2" tests="11" name="Test" time="54.759" errors="0" timestamp="2022-06-29T13:20:02 CEST">
  <testcase classname="testSuite.ToDosTest" name="verifyUI_Header_Label" time="0.372"/>
  <testcase classname="testSuite.ToDosTest" name="Verify_todo_item_should_get_added_in_the_list" time="1.235"/>
  <testcase classname="testSuite.ToDosTest" name="verify_functionality_of_Delete_ToDo_item" time="12.235"/>
  <testcase classname="testSuite.ToDosTest" name="verify_user_can_add_multiple_TODO_items_in_list" time="3.558"/>
  <testcase classname="testSuite.ToDosTest" name="verify_completed_TODO_items" time="0.165"/>
  <testcase classname="testSuite.ToDosTest" name="verify_functionality_of_Clear_Completed" time="0.174"/>
  <testcase classname="testSuite.ToDosTest" name="verify_functionality_of_Items_Left_count" time="2.276"/>
  <testcase classname="testSuite.ToDosTest" name="verify_revert_functionality_of_completed_TODE_item" time="1.167"/>
  <testcase classname="testSuite.ToDosTest" name="verify_Blank_or_null_TODO_item_not_get_added" time="13.508"/>
  <testcase classname="testSuite.ToDosTest" name="verify_Duplicate_TODO_item_not_get_added" time="12.308">
    <failure type="java.lang.AssertionError" message="Test Case Fail : TODOES accepting duplicate tasks expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: Test Case Fail : TODOES accepting duplicate tasks expected [1] but found [2]
at testSuite.ToDosTest.verify_Duplicate_TODO_item_not_get_added(ToDosTest.java:213)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verify_Duplicate_TODO_item_not_get_added -->
  <testcase classname="testSuite.ToDosTest" name="verify_SingleSpecialChar_in_TODO_item_not_get_added" time="3.455">
    <failure type="java.lang.AssertionError" message="Test Case Fail : TODOES accepting taks with special char only expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: Test Case Fail : TODOES accepting taks with special char only expected [0] but found [1]
at testSuite.ToDosTest.verify_SingleSpecialChar_in_TODO_item_not_get_added(ToDosTest.java:239)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verify_SingleSpecialChar_in_TODO_item_not_get_added -->
</testsuite> <!-- Test -->
